robot:
    interface: eno1
    joint_modules:
        motor_numbers: [0, 3, 2, 1, 5, 4, 6, 9, 8, 7, 11, 10]
        motor_constants: 0.025
        gear_ratios: 9.
        max_currents: 18.
        reverse_polarities: [
            false, true, true, true, false, false,
            false, true, true, true, false, false
        ]
        # +-0.9 for 0,3,6,9
        # +-1,45 for 1,4
        # lower_joint_limits: [
        #     -0.28, -2.8, -2.8, -0.9, -2.8, -2.8,
        #     -0.28, -2.8, -2.8, -0.9, -2.8, -2.8
        # ]
        # lower_joint_limits: [
        #     -2.8, -2.8, -2.8, -2.8, -2.8, -2.8,
        #     -2.8, -2.8, -2.8, -2.8, -2.8, -2.8
        # ]
        lower_joint_limits: [
            -0.28, -6.28, -6.28, -0.9, -6.28, -6.28,
            -0.28, -6.28, -6.28, -0.9, -6.28, -6.28
        ]
        # upper_joint_limits: [
        #     0.9,  2.8,  2.8,  0.28,  2.8,  2.8,
        #     0.9,  2.8,  2.8,  0.28,  2.8,  2.8
        # ]
        upper_joint_limits: [
            0.9, 6.28, 6.28, 0.28, 6.28, 6.28,
            0.9, 6.28, 6.28, 0.28, 6.28, 6.28
        ]
        max_joint_velocities: 180.    #80.
        safety_damping: 0.2   
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [1, 2, 3, 4]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [
      POS, NEG, POS, NEG, NEG, POS,
      POS, POS, POS, NEG, POS, POS
    ]
    # position_offsets: [    
    #    0.19972,  -0.30396,  0.34032,  -0.12473,  -0.42997,  0.51709,  0.34790,  0.54682,  0.29274,  -0.53586,  0.35914,  0.13969
      
    # ]    
    position_offsets: [
        0.22666, -0.293891, 0.295669, -0.16219, -0.463014, 0.517482, 0.349126, 0.537882, 0.306603, -0.147608, 0.111098, 0.116383
    ]
    #Joints:  [0.02946,  0.007125, -0.005335, 0.0001036, -0.004946,   0.01182]


    calib_order: [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]

    
    calib_pos: [
        0.0,  1.2, -2.4,
        0.0,  1.2, -2.4,
        0.0, -1.2,  2.4,
        0.0, -1.2,  2.4
    ]   
    Kp: 3  #5.
    Kd: 0.3
    T:  0.5 #1
    dt: 0.001
